name: Mono Environment
description: We invest in production
meta_description: "Mono Environment, We invest in production"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "https://monoenv.tech"
google_analytics: "G-XXXXXXXXXX"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: ""

# Disqus config
disqus-shortname: ""
